    const products = [
      { name: "Amethyst", price: "₹899", category: "stones", group: "Stones", icon: "✦" },
      { name: "Amazonite", price: "₹799", category: "stones", group: "Stones", icon: "◇" },
      { name: "Blood stone", price: "₹799", category: "stones", group: "Stones", icon: "●" },
      { name: "Red Carnelian", price: "₹799", category: "stones", group: "Stones", icon: "◈" },
      { name: "Cats eye", price: "₹999", category: "stones", group: "Stones", icon: "◉" },
      { name: "Natural Citrine", price: "₹1199", category: "stones", group: "Stones", icon: "✧" },
      { name: "Normal citrine", price: "₹999", category: "stones", group: "Stones", icon: "✧" },
      { name: "Dhan yog", price: "₹699", category: "healing", group: "Healing", icon: "∞" },
      { name: "Green avenchurain", price: "₹799", category: "stones", group: "Stones", icon: "✦" },
      { name: "Green jade", price: "₹699", category: "stones", group: "Stones", icon: "◆" },
      { name: "Green onyx", price: "₹799", category: "stones", group: "Stones", icon: "◈" },
      { name: "Hematite", price: "₹699", category: "stones", group: "Stones", icon: "◆" },
      { name: "Howlite", price: "₹799", category: "stones", group: "Stones", icon: "◇" },
      { name: "Karungali damru", price: "₹699", category: "accessories", group: "Accessories", icon: "⌁" },
      { name: "Karungali rudraksha", price: "₹699", category: "accessories", group: "Accessories", icon: "⌁" },
      { name: "Labradorite", price: "₹799", category: "stones", group: "Stones", icon: "✦" },
      { name: "Lapis", price: "₹899", category: "stones", group: "Stones", icon: "◈" },
      { name: "Money magnet", price: "₹699", category: "vastu", group: "Vaastu", icon: "∞" },
      { name: "Moonstone", price: "₹799", category: "stones", group: "Stones", icon: "◌" },
      { name: "Pyrite", price: "₹699", category: "stones", group: "Stones", icon: "✦" },
      { name: "Rhodonite", price: "₹699", category: "stones", group: "Stones", icon: "◆" },
      { name: "Rose", price: "₹699", category: "stones", group: "Stones", icon: "✧" },
      { name: "Sevan chakra", price: "₹799", category: "healing", group: "Healing", icon: "✦" },
      { name: "Smokey quartz", price: "₹999", category: "stones", group: "Stones", icon: "◇" },
      { name: "Sulemani", price: "₹799", category: "stones", group: "Stones", icon: "◆" },
      { name: "Tiger eye", price: "₹699", category: "stones", group: "Stones", icon: "◉" },
      { name: "Red jespar", price: "₹699", category: "stones", group: "Stones", icon: "●" },
      { name: "Rodocrosite", price: "₹799", category: "stones", group: "Stones", icon: "✧" },
      { name: "zibu keychain", price: "₹199", category: "accessories", group: "Accessories", icon: "☸" },
      { name: "Turquoise", price: "₹799", category: "stones", group: "Stones", icon: "◇" },
      { name: "Turquoise high", price: "₹1199", category: "stones", group: "Stones", icon: "◇" },
      { name: "Karungali full set (mala bracelet rudraksh, certificate)", price: "₹799", category: "bracelets", group: "Bracelets", icon: "⌁" },
      { name: "selenite leaf", price: "₹899", category: "healing", group: "Healing", icon: "◌" },
      { name: "selenite tower", price: "₹899", category: "healing", group: "Healing", icon: "△" },
      { name: "vastu kit", price: "₹1", category: "vastu", group: "Vaastu", icon: "⌂" },
      { name: "wish box", price: "₹5", category: "healing", group: "Healing", icon: "□" },
      { name: "oval money magnet", price: "₹10", category: "vastu", group: "Vaastu", icon: "∞" },
      { name: "tree", price: "₹19", category: "vastu", group: "Vaastu", icon: "✦" },
      { name: "pure quartz pyramid bracelet", price: "₹5", category: "bracelets", group: "Bracelets", icon: "△" },
      { name: "zodiac shine coin full set 2", price: "₹1299", category: "accessories", group: "Accessories", icon: "☸" },
      { name: "rashi set", price: "₹9999", category: "healing", group: "Healing", icon: "✦" },
      { name: "Mesha (Aries)", price: "₹899", category: "healing", group: "Rashi", icon: "♈", rashi: true },
      { name: "Vrishabha (Taurus)", price: "₹899", category: "healing", group: "Rashi", icon: "♉", rashi: true },
      { name: "Mithuna (Gemini)", price: "₹899", category: "healing", group: "Rashi", icon: "♊", rashi: true },
      { name: "Karka (Cancer)", price: "₹899", category: "healing", group: "Rashi", icon: "♋", rashi: true },
      { name: "Simha (Leo)", price: "₹899", category: "healing", group: "Rashi", icon: "♌", rashi: true },
      { name: "Kanya (Virgo)", price: "₹8999", category: "healing", group: "Rashi", icon: "♍", rashi: true },
      { name: "Tula (Libra)", price: "₹899", category: "healing", group: "Rashi", icon: "♎", rashi: true },
      { name: "Vrishchika (Scorpio)", price: "₹899", category: "healing", group: "Rashi", icon: "♏", rashi: true },
      { name: "Dhanu (Sagittarius)", price: "₹899", category: "healing", group: "Rashi", icon: "♐", rashi: true },
      { name: "Makara (Capricorn)", price: "₹899", category: "healing", group: "Rashi", icon: "♑", rashi: true },
      { name: "Kumbha (Aquarius)", price: "₹899", category: "healing", group: "Rashi", icon: "♒", rashi: true },
      { name: "Meena (Pisces)", price: "₹899", category: "healing", group: "Rashi", icon: "♓", rashi: true },
      { name: "Pyrite pen", price: "₹799", category: "accessories", group: "Accessories", icon: "✎" },
      { name: "green zibu coin", price: "₹199", category: "accessories", group: "Accessories", icon: "☸" },
      { name: "mulank bracelet 3 set", price: "₹9999", category: "bracelets", group: "Bracelets", icon: "⌁" },
      { name: "selenite plate ruff round", price: "₹199", category: "healing", group: "Healing", icon: "◌" },
      { name: "small pyamid", price: "₹899", category: "vastu", group: "Vaastu", icon: "△" },
      { name: "big pyramid", price: "₹999", category: "vastu", group: "Vaastu", icon: "△" },
      { name: "dhan yog chain girl bracelet", price: "₹899", category: "bracelets", group: "Bracelets", icon: "⌁" },
      { name: "dhan yog boy chain bracelet", price: "₹899", category: "bracelets", group: "Bracelets", icon: "⌁" },
      { name: "2 kg pyrite", price: "₹1999", category: "stones", group: "Stones", icon: "✦" },
      { name: "rose quartz pendent", price: "₹199", category: "accessories", group: "Accessories", icon: "◇" },
      { name: "varity natural tumble 10 each", price: "₹149", category: "stones", group: "Stones", icon: "◈" },
      { name: "peacock frame", price: "₹1299", category: "vastu", group: "Vaastu", icon: "□" },
      { name: "pyrite anklet", price: "₹599", category: "accessories", group: "Accessories", icon: "⌁" },
      { name: "vyapar vridji yantra", price: "₹1199", category: "vastu", group: "Vaastu", icon: "△" },
      { name: "kuber pendent", price: "₹5", category: "vastu", group: "Vaastu", icon: "◇" },
      { name: "7 chakra diye", price: "₹15", category: "healing", group: "Healing", icon: "✦" },
      { name: "7 chakra hanger", price: "₹5", category: "healing", group: "Healing", icon: "✦" }
    ];

    const productImages = {
      "Amethyst": "crystal_images/amethyst.png",
      "Amazonite": "crystal_images/amazonite.png",
      "Blood stone": "crystal_images/bloodstone.png",
      "Red Carnelian": "crystal_images/red_carnelian.png",
      "Cats eye": "crystal_images/cat_eye.jpg",
      "Natural Citrine": "crystal_images/natural_citrine.png",
      "Normal citrine": "crystal_images/normal_citrine.png",
      "Dhan yog": "crystal_images/dhanyog.png",
      "Green avenchurain": "crystal_images/green_aventurine.png",
      "Green jade": "crystal_images/green_jade.png",
      "Green onyx": "crystal_images/green_onyx.png",
      "Hematite": "crystal_images/Hematite.png",
      "Howlite": "crystal_images/howlite.png",
      "Labradorite": "crystal_images/labrodorite.png",
      "Lapis": "crystal_images/lapis.jpg",
      "Moonstone": "crystal_images/moonstone.jpg",
      "Pyrite": "crystal_images/pyrite.png",
      "Rhodonite": "crystal_images/rhodonite.jpg",
      "Rose": "crystal_images/rose.png",
      "Sevan chakra": "crystal_images/seven_chakra.jpg",
      "Smokey quartz": "crystal_images/smoky_quartz.jpg",
      "Sulemani": "crystal_images/sulemani.jpg",
      "Tiger eye": "crystal_images/tiger_eye.jpg",
      "Red jespar": "crystal_images/red_jasper.jpg",
      "Rodocrosite": "crystal_images/rhodocrosite.jpg",
      "Turquoise": "crystal_images/turquoise.jpg",
      "Turquoise high": "crystal_images/turquoise_high.jpg",
      "peacock frame": "crystal_images/peacock_frame.jpg",
      "pyrite anklet": "crystal_images/pyrite_anklets.jpg",
      "Mesha (Aries)": "crystal_images/aries(mesha).jpg",
      "Mithuna (Gemini)": "crystal_images/gemini.jpg",
      "Kanya (Virgo)": "crystal_images/virgo.jpg",
      "Tula (Libra)": "crystal_images/libra.jpg",
      "Vrishchika (Scorpio)": "crystal_images/scorpio.jpg",
      "Dhanu (Sagittarius)": "crystal_images/sagittarius.jpg",
      "Kumbha (Aquarius)": "crystal_images/aquarius.jpg"
    };

    products.forEach(product => {
      if (productImages[product.name]) product.image = productImages[product.name];
    });

    // Curated descriptions dictionary
    const productDescriptions = {
      "Amethyst": "Renowned for its calming frequency, Amethyst aids in mental clarity, deep intuition, and peaceful meditation.",
      "Amazonite": "A stone of courage and truth, Amazonite empowers self-expression, emotional balance, and physical harmony.",
      "Natural Citrine": "Carrying the radiant energy of the sun, Natural Citrine fosters optimism, abundance, and financial flow.",
      "Pyrite": "Known as the stone of prosperity and willpower, Pyrite shields against negative energy while amplifying focus.",
      "Rose": "Restores trust, unconditional love, and inner peace, encouraging compassionate heart energy.",
      "Tiger eye": "A grounding stone that combines earth and solar energy to draw steady prosperity, protection, and confidence.",
      "Money megnet": "Sacred Vaastu configuration engineered to attract financial flow, positive opportunities, and clarity.",
      "Karungali rudraksha": "Traditional ebony wood and rudraksha beads crafted for powerful spiritual grounding and protective energy.",
      "selenite tower": "High-vibration selenite tower designed to continuously clear negative energy and charge your space.",
      "Lapis": "A gemstone of royalty and wisdom, Lapis Lazuli stimulates deep inner truth, intellect, and spiritual alignment.",
      "Moonstone": "Associated with lunar cycles, Moonstone promotes inner growth, emotional stability, and intuitive perception."
    };
